#!/usr/bin/env python2
import os
import sys

__dirname=os.path.dirname(os.path.abspath(__file__))

# Add local Js2Py to load path
sys.path.insert(0, os.path.join(__dirname, "Js2Py"))
import js2py

print js2py.translate_file(os.path.join(__dirname, "..", "dist", "docopt.purs.js"))
